---
- hosts: localhost
  vars:
    state_store: "s3://{{ s3name }}"
  vars_files:
    - variables.yml
    - secret.yaml
  vars_prompt:
    - name: "cluster_name"
      prompt: "provide the partial cluster identifier"
      private: no
  
  tasks:
    - name: export kubeconfig
      command:
        cmd: kops export kubecfg --admin --name={{ cluster_name }} --state=s3://{{ s3name }} --kubeconfig /tmp/{{ cluster_name }}.yaml