---
- hosts: localhost
  vars:
    state_store: "s3://{{ s3name }}"
  vars_files:
    - variables.yml
    - secret.yaml
  vars_prompt:
    - name: "cluster_name"
      prompt: "provide the partial cluster identifier"
      private: no
  tasks:

    - name: Set kops path for Linux
      set_fact:
        kops_path: "/usr/local/bin/kops"
      when: ansible_distribution == 'Ubuntu'
    - name: Set kops path for macOS
      set_fact:
        kops_path: "/opt/homebrew/bin/kops"
      when: ansible_distribution == 'MacOSX'

    - name: export kubeconfig
      command:
        cmd: "{{ kops_path }} export kubecfg --admin --name={{ cluster_name }} --state=s3://{{ s3name }} --kubeconfig /tmp/{{ cluster_name }}.yaml"

    - name: "location_msg"
      debug:
        msg:
          -  " exported to /tmp/{{ cluster_name }}.yaml"