- hosts: localhost
  vars:
    state_store: "s3://{{ s3name }}"
  vars_files:
    - variables.yml
    - secret.yaml

  vars_prompt:
    - name: "cluster_name"
      prompt: "provide the partial cluster identifier"
      private: no

  tasks:
    - name: export kubeconfig
      command:
        cmd: kops export --name {{ cluster_name }} kubecfg --admin --state s3://{{ s3name }} --kubeconfig /tmp/{{ cluster_name }}.yaml

    - name: Add Istio Helm Repository
      command:
        cmd: helm repo add istio https://istio-release.storage.googleapis.com/charts
      register: helm_repo_add_output
      ignore_errors: true

    - name: Display result of adding Helm Repo
      debug:
        msg: "{{ helm_repo_add_output.stdout_lines }}"

    - name: Update Helm Repository
      command:
        cmd: helm repo update
      register: helm_repo_update_output

    - name: Display result of updating Helm Repo
      debug:
        msg: "{{ helm_repo_update_output.stdout_lines }}"

    - name: Create Istio Namespace
      command:
        cmd: kubectl create namespace istio-system
      environment:
        KUBECONFIG: "/tmp/{{ cluster_name }}.yaml"
      ignore_errors: true

    - name: Install Istio Base
      command:
        cmd: helm install istio-base istio/base -n istio-system --set defaultRevision=default
      environment:
        KUBECONFIG: "/tmp/{{ cluster_name }}.yaml"
      register: install_istio_base_output


    - name: Display result of installing Istio Base
      debug:
        msg: "{{ install_istio_base_output.stdout_lines }}"

    - name: Install istio discovery chart
      command:
        cmd: helm install istiod istio/istiod -n istio-system --wait
      environment:
        KUBECONFIG: "/tmp/{{ cluster_name }}.yaml"
      
    - name: install kiali
      command: 
        cmd: kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.19/samples/addons/kiali.yaml
      environment:
        KUBECONFIG: "/tmp/{{ cluster_name }}.yaml"

    - name: install prometheus
      command: 
        cmd: kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.19/samples/addons/prometheus.yaml
      environment:
        KUBECONFIG: "/tmp/{{ cluster_name }}.yaml"
