---
- name: List all kops clusters
  hosts: localhost
  vars_files:
    - variables.yml
    - secret.yaml
  tasks:
    - name: Run kops get clusters to list all clusters
      command:
        cmd: kops get clusters --state s3://{{ s3name}}
      register: clusters_output

    - name: Display all clusters
      debug:
        msg: "{{ clusters_output.stdout_lines }}"
